include config.mk

OBJ0=$(SRC0:.c=.o)
OBJ1=$(SRC1:.c=.o)
OBJ2=$(SRC2:.c=.o)
OBJ3=$(SRC3:.c=.o)
OBJ4=$(SRC4:.c=.o)
OBJ5=$(SRC5:.c=.o)
OBJ6=$(SRC6:.c=.o)
OBJ7=$(SRC7:.c=.o)
OBJ8=$(SRC8:.c=.o)
OBJ9=$(SRC9:.c=.o)
OBJ10=$(SRC10:.c=.o)
OBJ11=$(SRC11:.c=.o)
OBJ12=$(SRC12:.c=.o)
OBJ13=$(SRC13:.c=.o)
OBJ14=$(SRC14:.c=.o)
OBJ15=$(SRC15:.c=.o)
OBJ16=$(SRC16:.c=.o)
OBJ17=$(SRC17:.c=.o)
OBJ18=$(SRC18:.c=.o)
OBJ19=$(SRC19:.c=.o)

all:

.c.o:
	@echo CC	$@
	@${CC} ${FLAGS} ${CFLAGS} ${INCS} $< -c -o $@

${OBJ0}: config.mk
${BIN0}: CFLAGS=${DBG_CFLAGS}
${BIN0}: ${OBJ0}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ1}: config.mk
${BIN1}: CFLAGS=${DBG_CFLAGS}
${BIN1}: ${OBJ1}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ2}: config.mk
${BIN2}: CFLAGS=${DBG_CFLAGS}
${BIN2}: ${OBJ2}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ3}: config.mk
${BIN3}: CFLAGS=${DBG_CFLAGS}
${BIN3}: ${OBJ3}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ4}: config.mk
${BIN4}: CFLAGS=${DBG_CFLAGS}
${BIN4}: ${OBJ4}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ5}: config.mk
${BIN5}: CFLAGS=${DBG_CFLAGS}
${BIN5}: ${OBJ5}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ6}: config.mk
${BIN6}: CFLAGS=${DBG_CFLAGS}
${BIN6}: ${OBJ6}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ7}: config.mk
${BIN7}: CFLAGS=${DBG_CFLAGS}
${BIN7}: ${OBJ7}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ8}: config.mk
${BIN8}: CFLAGS=${DBG_CFLAGS}
${BIN8}: ${OBJ8}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ9}: config.mk
${BIN9}: CFLAGS=${DBG_CFLAGS}
${BIN9}: ${OBJ9}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ10}: config.mk
${BIN10}: CFLAGS=${DBG_CFLAGS}
${BIN10}: ${OBJ10}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ11}: config.mk
${BIN11}: CFLAGS=${DBG_CFLAGS}
${BIN11}: ${OBJ11}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ12}: config.mk
${BIN12}: CFLAGS=${DBG_CFLAGS}
${BIN12}: ${OBJ12}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ13}: config.mk
${BIN13}: CFLAGS=${DBG_CFLAGS}
${BIN13}: ${OBJ13}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ14}: config.mk
${BIN14}: CFLAGS=${DBG_CFLAGS}
${BIN14}: ${OBJ14}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ15}: config.mk
${BIN15}: CFLAGS=${DBG_CFLAGS}
${BIN15}: ${OBJ15}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ16}: config.mk
${BIN16}: CFLAGS=${DBG_CFLAGS}
${BIN16}: ${OBJ16}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ17}: config.mk
${BIN17}: CFLAGS=${DBG_CFLAGS}
${BIN17}: ${OBJ17}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ18}: config.mk
${BIN18}: CFLAGS=${DBG_CFLAGS}
${BIN18}: ${OBJ18}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

${OBJ19}: config.mk
${BIN19}: CFLAGS=${DBG_CFLAGS}
${BIN19}: ${OBJ19}
	@echo Linking...
	@${CC} ${FLAGS} ${LIBSPATH} ${LIBS} ${DBG_LFLAGS} $? \
    -o $@
	@echo $@

clean:
	@echo Cleaning...
	rm -rf ${OBJ0} ${BIN0} \
  	${OBJ1} ${BIN1} \
  	${OBJ2} ${BIN2} \
  	${OBJ3} ${BIN3} \
  	${OBJ4} ${BIN4} \
  	${OBJ5} ${BIN5} \
  	${OBJ6} ${BIN6} \
  	${OBJ7} ${BIN7} \
  	${OBJ8} ${BIN8} \
  	${OBJ9} ${BIN9} \
  	${OBJ10} ${BIN10} \
  	${OBJ11} ${BIN11} \
  	${OBJ12} ${BIN12} \
  	${OBJ13} ${BIN13} \
  	${OBJ14} ${BIN14} \
  	${OBJ15} ${BIN15} \
  	${OBJ16} ${BIN16} \
  	${OBJ17} ${BIN17} \
  	${OBJ18} ${BIN18} \
  	${OBJ19} ${BIN19}

.SUFFIXES: .c .o
.PHONY: all clean
